### ISSUE TITLE
Can you post the contents of the data folder so we can run the tests?

### ISSUE THREAD

**Issue by snuped** [protectai/modelscan#146] opened 2024-05-06 14:51 UTC
Hello,

I see the test file, but not the data in which it tests. Can you upload that to Google drive?

Thanks!

**Comment by snuped** [comment] 2024-05-09 11:40
At least post the safe_model.h5 and unsafe_model.h5 so that we can use the notebooks?

**Comment by iamfaisalkhan** [comment] 2024-05-09 15:07
@snuped We intentionally didn't put the unsafe model in the repo. However, you can generate them by running the notebooks e.g. this [notebook](https://github.com/protectai/modelscan/blob/main/notebooks/keras_fashion_mnist.ipynb) generates both the `safe_model.h5` and `unsafe_model.h5` files and run the scan.

**Comment by iamfaisalkhan** [comment] 2024-05-09 15:12
Closing this issue since it is not a bug.

**Closed by iamfaisalkhan** 2024-05-09 15:12 UTC
Labels: bug
