### ISSUE TITLE
Files are getting skipped from scanning

### ISSUE THREAD

**Issue by santikris2003** [protectai/modelscan#134] opened 2024-04-09 12:52 UTC
I'm running modelscan against a MI Model Library , most of the files are getting skipped and Im getting this ,anyreason why this happening 
kris@macuser Downloads % modelscan scan -p /Users/kris/Downloads/checkpoints --show-skipped
No settings file detected at /Users/kris/Downloads/modelscan-settings.toml. Using defaults.

--- Summary ---

 No issues found! 🎉

--- Skipped ---

Total skipped: 20 - run with --show-skipped to see the full list.

Skipped files list:

The following file /Users/kris/Downloads/checkpoints/.DS_Store was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00017_000 was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00001_000 was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00011_000 was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00005_000 was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00010_000 was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00006_000 was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00012_000 was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00013_000 was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00007_000 was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00022_000 was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00023_000 was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00021_000 was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00009_000 was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00008_000 was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00020_000 was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00018_000 was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00024_000 was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00025_000 was skipped during a ModelScan scan:
Model Scan did not scan file
The following file /Users/kris/Downloads/checkpoints/ckpt-0/tensor00019_000 was skipped during a ModelScan scan:
Model Scan did not scan file
kris@macuser Downloads %

**Comment by mniels17** [comment] 2024-04-16 19:59
Same here.  Is this expected behavior?

**Comment by swashko** [comment] 2024-04-16 20:27
That's expected behavior since they don't have any of the supported extensions

**Comment by seanpmorgan** [comment] 2024-04-25 04:18
Closing as this is expected. Feel free to open a feature request if there is a scan you'd like to see

**Closed by seanpmorgan** 2024-04-25 04:18 UTC
Labels: bug

**Comment by rao-pathangi** [comment] 2024-10-17 11:42
> That's expected behavior since they don't have any of the supported extensions

@swashko :

Is there a way to identify the missing extension? I suppose the extension in this case is related to tensorflow based on the extension ckpt for checkpoints. Once the extension is known, is this something modelscan should include support for or can the users of modelscan install the extension themselves?
